# Use X-Forwarded-*-headers for absolute URL resolution
server:
  forward-headers-strategy: framework
  shutdown: graceful
  port: ${PORT:8080}
  error:
    include-message: always

spring:
  application:
    name: plantevernjournal-api

  cloud:
    gcp:
      core:
        enabled: true

  profiles:
    active: dev

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  show-actuator: true
